services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    volumes:
      - ./backend/rutube_bot/:/code/rutube_bot
    restart: always

  tg_bot:
    build:
      context: ./tg_bot
      dockerfile: ./Dockerfile
    env_file:
      - .env.prod
    restart: always
