version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    volumes:
      - ./backend/rutube_bot/:/code/rutube_bot
      - ./backend/chroma_data:/code/chroma_data
    restart: always
    networks:
      - backend-redis

  tg_bot:
    build:
      context: ./tg_bot
      dockerfile: ./Dockerfile
    env_file:
      - .env.prod
    restart: always
    networks:
      - default

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - ./redis_data:/data
    networks:
      - backend-redis

networks:
  backend-redis:
    internal: true
  default:
    driver: bridge